// Mocks generated by Mockito 5.3.2 from annotations
// in ab_smartly/context_data_provider.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ab_smartly/context_data_provider.dart' as _i3;
import 'package:ab_smartly/json/context_data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextData_0 extends _i1.SmartFake implements _i2.ContextData {
  _FakeContextData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContextDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextDataProvider extends _i1.Mock
    implements _i3.ContextDataProvider {
  @override
  _i4.Future<_i2.ContextData> getContextData() => (super.noSuchMethod(
        Invocation.method(
          #getContextData,
          [],
        ),
        returnValue: _i4.Future<_i2.ContextData>.value(_FakeContextData_0(
          this,
          Invocation.method(
            #getContextData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ContextData>.value(_FakeContextData_0(
          this,
          Invocation.method(
            #getContextData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ContextData>);
}
